### ISSUE TITLE
Guild Names

### ISSUE THREAD

**Issue by Xyliea** [Ulminia/blizzard-api-oauth#10]
Hi,
I'm currently trying to see my guild's stats, but I'm getting an error.

`$r = $client->fetch('guild',array('name'=>'morally grey','server'=>'magtheridon'));`
This displays on my site
Array
(
    [status] => nok
    [reason] => Guild not found.
    [header] => Array
        (
            [http_code] => HTTP/1.1 404 Not Found
            [Date] => Fri, 31 May 2019 10:44:40 GMT
            [Server] => Apache-Coyote/1.1
            [content-type] => application/json;charset=utf-8
            [content-length] => 46
            [x-trace-traceid] => 159d2333-2357-b820-47d8-fa165b971340
            [x-trace-spanid] => 159d2333-2357-bc40-47d8-fa165b971340
            [x-trace-parentspanid] => 159d2333-2357-bc10-47d8-fa165b971340
            [x-frame-options] => SAMEORIGIN
            [X-Content-Type-Options] => nosniff
            [connection] => keep-alive
        )

    [http_code] => 404
    [last_url] => https://eu.api.blizzard.com/wow/guild/magtheridon/morally-grey?apikey=c31b97338ab04bb0aea61432ac8bae2b&access_token=EUikZcqKANYbw0qsepeRzvFLUJ116sACaX&locale=en_GB
)

My code works with 1 word guilds e.g. name=>method server=>tarren mill, but I'm not sure how to format putting in my guild's name with a space.

Thanks

**Comment by Ulminia** [comment]
i think blizzard has changed the coding for guild names to be something else ial test and apply a fix soon
you can also find me on the unofficial api discord link on the api forums

**Comment by Ulminia** [comment]
patch has been applied let me know if this works

**Comment by Ulminia** [comment]
names in new api are converted to slugs as needed
