### ISSUE TITLE
Hard to get to work without example

### ISSUE THREAD

**Issue by muldereric** [Ulminia/blizzard-api-oauth#2]
This is not really an issue but feedback on your wiki.
Though the wiki is setup properly and contains those steps the one has to follow, I am missing an example on the Setup section and Usage <game> sections.

**Comment by Ulminia** [comment]
there are code bits as to what you need to include in the file where you will be making calls from i have not included a full file example if you include the set code in setup in a file adding the proper vars from blizzard and your website then follow the usage and type usage pages for making calls
