### ISSUE TITLE
Problem to fetch Data on the Wiki Point "Usage"

### ISSUE THREAD

**Issue by DevBaka** [Ulminia/blizzard-api-oauth#5]
Hey There,
i try out youre api framework.  On the Usage wiki you write the line with: 
"$r = $client->fetch($type,$parameters);"
I have write this and have created the array with the name $parameters. But i didnt find/know what you meaning with the $type value?

Thanks for Help and sorry for my bad englisch.

EDIT:
I have found the resolution for my problem.
I havent understand, that the types that you means are the Types, right on the side like on "Usage Warcraft" and then i will insert there a String with "achievement" if i want see the archivemnts from the player or so.  Maybe i would write this part with more details. Its hard to understand, but i like youre Framework, because it works easy, after the basic setup

**Comment by Ulminia** [comment]
ty i have updated the page to be more clear i hope
