### ISSUE TITLE
Code example does not reflect usage

### ISSUE THREAD

**Issue by ryanpiv** [Ulminia/blizzard-api-oauth#6]
Hello, the code example give in the README.md seen at https://github.com/Ulminia/blizzard-api-oauth appears to be outdated.  The particular line:

`$response = $client->fetch('user',array('source'=>'account'));`

will return the error:

`Unidentified variable $q`

which is expected when the switch statement in ext/account.php has no option for 'user.'  Upon changing the statement to 'account' I was able to retrieve expected results.

**Comment by Ulminia** [comment]
changed preview
