### ISSUE TITLE
urlbase has changed.. please adjust client.php 

### ISSUE THREAD

**Issue by toxrocks** [Ulminia/blizzard-api-oauth#8]
Client.php baseurl adresses have changed. Please adjust :)

OLD: 'urlbase'	=> 'https://us.api.battle.net/',
NEW: 'urlbase'	=> 'https://us.api.blizzard.com/',

**Comment by Ulminia** [comment]
i am aware of the changes until January 2019 old urls work
new re code incoming soon<sup>tm</sup> to use new urls and token

**Comment by toxrocks** [comment]
Well i get an "account inactive" message when trying with old .battle.net url ... 
i´m using a brandnew develop.battle.net account... maybe there is a difference here.

but ok, looking forward for the recoding :)

Thanks for the response

**Comment by Ulminia** [comment]
old secret and client codes do not work on new url and vise versa
next week i should have a beta for the new code in a new branch

**Comment by toxrocks** [comment]
Thank you very much

**Comment by Ulminia** [comment]
project updated to new standards 2022
