### ISSUE TITLE
IGrantType...

### ISSUE THREAD

**Issue by Greenou** [Ulminia/blizzard-api-oauth#9]
Hi,

When i update your code, i have this error : 

> Fatal error: Cannot declare interface IGrantType, because the name is already in use in /GrantType/IGrantType.php on line 6

Please help me :'(

**Comment by Ulminia** [comment]
i just pushed some changes see if that fixed it for you or paste the entire error for me

**Comment by Greenou** [comment]
Gratz !! Thank you so much about that :)
